### ISSUE TITLE
Why does minary not run if I haven't winpcap?

### ISSUE THREAD

**Issue by ghost** [Minary/Minary#22]
IHello everyone,

wow nice idea but I have problem with f***ing WinPcap I really don't understand I have already installed but It does not work.
![probloem_minary](https://user-images.githubusercontent.com/3496136/37259762-da1a3d84-258a-11e8-8b69-e23a19bb2db5.PNG)

I already download WinPcap from 10.2 I tried .. no success how do I fix?

What is correct version of WinPcap?

**Comment by rubenunteregger** [comment]
Hi

I use the most recent version 4.1.3 (https://www.winpcap.org/install/default.htm)

**Comment by ghost** [comment]
Thanks I will try
